### ISSUE TITLE
AccessViolationException in stringComparer

### ISSUE THREAD

**Issue by bslatner** [matthewcrews/FastDictionaryTest#4]
Hi, Matthew. First, thanks for doing this. I've sped up a lot of code with your work.

I don't have a whole lot of information to share about this issue, but here's what I know. In a recent project, I've really ramped up usage of dictionaries -- based on ByteListRobinHoodVec128. I have about 7 of them, some with about 50k elements, some with about half a million.

On my first "big" test run, I received a System.AccessViolationException in the implementation of GetHashCode for the stringComparer. (function startes line 68 in ByteListRobinHoodVec128.fs)

I don't have a lot more information than that. I can tell you that the dictionary had about 50k elements, that the keys were all string representations of int64 values, and the values were structs of about 1k each. I'm not sure any of that is relevant :)

I've stared at the GetHashCode implementation for a long while and I'll be darned if I can see a problem. If I replace it with one of the StringComparer implementations in System the problem disappears. The exception does say that "this is often and indication that other memory is corrupt", but I'm not sure where that would be. All the rest of the code is either standard .NET 6.0 stuff or MongoDB queries.

If you have any insight, I'd love to hear it.

**Comment by matthewcrews** [comment]
I'm glad you have found my content helpful.

I would recommend not using the Vec128 version of the Dictionary. There are other versions that are faster. Vec128 relies on memory layout being controlled to make SIMD work as intended. I have found that SIMD adds a significant amount of complication without much performance benefit.

Later versions of the Dictionary are faster and do not rely on SIMD.
