### ISSUE TITLE
Infinite loop when dictionary is empty

### ISSUE THREAD

**Issue by bslatner** [matthewcrews/FastDictionaryTest#6]
I started using the implementation in ByteListRobinHoodInline.fs per your suggestion in the previous issue I raised.

When the dictionary is empty, Bucket.IsLast never seems to evaluate to `true`. As a result, lookups in an empty dictionary cause an infinite loop.

I added a check for count = 0 where it checks IsLast in the main body of the Item function and that seems to have sorted it. But obviously that adds another `CMP` instruction and that's not optimal, is it? :) I was wondering if you knew of another way to do it.

**Comment by matthewcrews** [comment]
Interesting. I'll have to look at that.

Just an FYI, I wouldn't consider this code to be production-worthy yet. This has been me playing around with different ideas and trying alternative approaches. I'd recommend checking out the FrozenDictionary in .NET 8 if you want something more robust.

In the long term, I hope to offer these optimizations to the .NET team for their FrozenDictionary.

I'm still playing with ideas as I have time so this still isn't even the final form.

**Comment by bslatner** [comment]
Oh, I was sure it wasn't production ready. But I like to live dangerously. Unfortunately, I'm stuck on .NET 6.0.
